# Generated by Django 5.1.2 on 2024-10-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_chat_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
