# Generated by Django 5.1.2 on 2024-10-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chat_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='user_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
