# Generated by Django 5.1.2 on 2024-10-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_user_chat_user_id_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='user',
        ),
    ]
